pipeline {
    agent any
    tools {
    maven 'local_maven' 
  }
    
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: 'target/*.war', allowEmptyArchive: true
                }
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.bat'
                deploy adapters: [tomcat9(credentialsId: '167cb693-7531-4239-a861-d69ec6b5f0e8', path: '', url: 'http://localhost:88/')], contextPath: null, war: '**/*.war'
            }
        }
    }
}
